name: mustang_cli
description: A sample command-line application.
version: 1.0.0
homepage: https://bitbucket.org/lunchclub/mustang_cli/src/master/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4

executables:
  mcli: mustang_cli
